import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Chat.module.css";
import {
  Nav,
  NavItem,
  NavLink,
  TabPane,
  Row,
  TabContent,
  Col,
} from "reactstrap";
import React, { useEffect, useState } from "react";
import axios from "axios";
import dateFormat, { masks } from "dateformat";
import { useRouter } from "next/router";

export async function getServerSideProps(context) {
  const token = context.req.cookies.token;
  const user = context.req.cookies.users;
  const api1 = async () => {
    try {
      const res = await axios({
        method: "get",
        url: `${process.env.HOST}/worker/${user}`,
        headers: { token: token },
      });
      return {
        data: res.data,
        error: false,
      };
    } catch (error) {
      return {
        data: [],
        error: true,
      };
    }
  };
  return {
    props: {
      data: [],
      api1: await api1(),
    },
  };
}

function Chat(props) {
  const router = useRouter();
  const [activeTab, setActiveTab] = useState("1");
  const data1 = props.api1.data.data;
  const host = process.env.HOST;

  return (
    <>
      <Head>
        <title>profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className="hero"
        style={{ height: "200vh", backgroundColor: "#E5E5E5" }}
      >
        <div className={styles.container}>
          <div className={styles.profile}>
            <div className={styles.cover}>
              <h3>Data Diri</h3>
            </div>
            <div className={styles.line}></div>
            <div className={styles.cover}>
              <div style={{ marginRight: "30px" }}>
                <Image
                  src={`${process.env.HOST}/profile.jpg`}
                  style={{ borderRadius: "50%" }}
                  width={50}
                  height={50}
                  layout="fixed"
                  alt="gambar"
                ></Image>
              </div>
              <h3>Jonas Adam</h3>
            </div>
          </div>
          <div className={styles.content}>
            <div className={styles.cover}>
              <div style={{ marginRight: "30px" }}>
                <Image
                  src={`${process.env.HOST}/profile.jpg`}
                  style={{ borderRadius: "50%" }}
                  width={50}
                  height={50}
                  layout="fixed"
                  alt="gambar"
                ></Image>
              </div>
              <h3>Jonas Adam</h3>
            </div>
            <div className={styles.line}></div>
          </div>
        </div>
      </div>
    </>
  );
}
Chat.layout = "L1";

export default Chat;
