import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Landing.module.css";
import { useRouter } from "next/router";

function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <div className={styles.jumbotron}>
          <div className={styles.content}>
            <h1 className={styles.title}>
              Talenta terbaik negri untuk perubahan revolusi 4.0
            </h1>
            <h6 className={styles.desc}>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
              euismod ipsum et dui rhoncus auctor.
            </h6>
            <button className={styles.button} onClick={() => router.push('/home')}>
              Mulai Dari Sekarang
            </button>
          </div>
          <div className={styles.image}>
            <Image
              src="/landing1.png"
              width={600}
              height={600}
              layout="fixed"
              alt="gambar"
            ></Image>
          </div>
        </div>
        <div className={styles.jumbotron}>
          <div className={styles.image}>
            <Image
              src="/landing2.png"
              width={600}
              height={520}
              layout="fixed"
              alt="gambar"
            ></Image>
          </div>
          <div className={styles.content}>
            <h1 className={styles.title}>
              Kenapa harus mencari tallent di peworld
            </h1>
            <ul className={styles.list}>
              <li className={styles.formText}>
                <div className={styles.icon}>
                  <Image
                    src="/purpleIcon.png"
                    width={24}
                    height={24}
                    layout="fixed"
                    alt="gambar"
                  ></Image>
                </div>
                <div>Lorem ipsum dolor sit amet.</div>
              </li>
              <li className={styles.formText}>
                <div className={styles.icon}>
                  <Image
                    src="/purpleIcon.png"
                    width={24}
                    height={24}
                    layout="fixed"
                    alt="gambar"
                  ></Image>
                </div>
                <div>Lorem ipsum dolor sit amet.</div>
              </li>
              <li className={styles.formText}>
                <div className={styles.icon}>
                  <Image
                    src="/purpleIcon.png"
                    width={24}
                    height={24}
                    layout="fixed"
                    alt="gambar"
                  ></Image>
                </div>
                <div>Lorem ipsum dolor sit amet.</div>
              </li>
              <li className={styles.formText}>
                <div className={styles.icon}>
                  <Image
                    src="/purpleIcon.png"
                    width={24}
                    height={24}
                    layout="fixed"
                    alt="gambar"
                  ></Image>
                </div>
                <div>Lorem ipsum dolor sit amet.</div>
              </li>
            </ul>
          </div>
        </div>
        <div className={styles.jumbotron}>
          <div className={styles.content}>
            <h1 className={styles.title}>Skill Tallent</h1>
            <h6 className={styles.desc}>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
              euismod ipsum et dui rhoncus auctor.
            </h6>
            <div className={styles.skill}>
              <ul className={styles.listSkill}>
                <li className={styles.formText}>
                  <div className={styles.icon}>
                    <Image
                      src="/orangeIcon.png"
                      width={24}
                      height={24}
                      layout="fixed"
                      alt="gambar"
                    ></Image>
                  </div>
                  <div>Java</div>
                </li>
                <li className={styles.formText}>
                  <div className={styles.icon}>
                    <Image
                      src="/orangeIcon.png"
                      width={24}
                      height={24}
                      layout="fixed"
                      alt="gambar"
                    ></Image>
                  </div>
                  <div>Kotlin</div>
                </li>
                <li className={styles.formText}>
                  <div className={styles.icon}>
                    <Image
                      src="/orangeIcon.png"
                      width={24}
                      height={24}
                      layout="fixed"
                      alt="gambar"
                    ></Image>
                  </div>
                  <div>PHP</div>
                </li>
                <li className={styles.formText}>
                  <div className={styles.icon}>
                    <Image
                      src="/orangeIcon.png"
                      width={24}
                      height={24}
                      layout="fixed"
                      alt="gambar"
                    ></Image>
                  </div>
                  <div>JavaScript</div>
                </li>
              </ul>
              <ul className={styles.listSkill}>
                <li className={styles.formText}>
                  <div className={styles.icon}>
                    <Image
                      src="/orangeIcon.png"
                      width={24}
                      height={24}
                      layout="fixed"
                      alt="gambar"
                    ></Image>
                  </div>
                  <div>Golang</div>
                </li>
                <li className={styles.formText}>
                  <div className={styles.icon}>
                    <Image
                      src="/orangeIcon.png"
                      width={24}
                      height={24}
                      layout="fixed"
                      alt="gambar"
                    ></Image>
                  </div>
                  <div>c++</div>
                </li>
                <li className={styles.formText}>
                  <div className={styles.icon}>
                    <Image
                      src="/orangeIcon.png"
                      width={24}
                      height={24}
                      layout="fixed"
                      alt="gambar"
                    ></Image>
                  </div>
                  <div>Ruby</div>
                </li>
                <li className={styles.formText}>
                  <div className={styles.icon}>
                    <Image
                      src="/orangeIcon.png"
                      width={24}
                      height={24}
                      layout="fixed"
                      alt="gambar"
                    ></Image>
                  </div>
                  <div>10+ Bahasa lainnya</div>
                </li>
              </ul>
            </div>
          </div>
          <div className={styles.image}>
            <Image
              src="/landing3.png"
              width={600}
              height={520}
              layout="fixed"
              alt="gambar"
            ></Image>
          </div>
        </div>
        <div className={styles.hero}>
          <h1>Their opinion about peworld</h1>
          <div className={styles.formOpinion}>
            <button className={styles.button3}>
              <Image
                src="/next2.svg"
                width={30}
                height={30}
                layout="fixed"
                alt="gambar"
              ></Image>
            </button>

            <div className={styles.card}>
              <div className={styles.profileOpinion}>
                <Image
                  src="/profile1.png"
                  width={170}
                  height={170}
                  layout="fixed"
                  alt="gambar"
                ></Image>
              </div>
              <h2 className={styles.name}>Harry Styles</h2>
              <div className={styles.jobDesk}>Web Developer</div>
              <div className={styles.opinion}>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
                euismod ipsum et dui rhoncus auctor.
              </div>
            </div>
            <div className={styles.card}>
              <div className={styles.profileOpinion}>
                <Image
                  src="/profile2.png"
                  width={170}
                  height={170}
                  layout="fixed"
                  alt="gambar"
                ></Image>
              </div>
              <h2 className={styles.name}>Niall Horan</h2>
              <div className={styles.jobDesk}>Web Developer</div>
              <div className={styles.opinion}>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              </div>
            </div>
            <div className={styles.card}>
              <div className={styles.profileOpinion}>
                <Image
                  src="/profile3.png"
                  width={170}
                  height={170}
                  layout="fixed"
                  alt="gambar"
                ></Image>
              </div>
              <h2 className={styles.name}>Louis Tomlinson</h2>
              <div className={styles.jobDesk}>Web Developer</div>
              <div className={styles.opinion}>
                Lorem ipsum dolor sit amet, consectetur
              </div>
            </div>

            <button className={styles.button3}>
              <Image
                src="/next1.svg"
                width={30}
                height={30}
                layout="fixed"
                alt="gambar"
              ></Image>
            </button>
          </div>
        </div>
        <div className={styles.box}>
          <div className={styles.cover}>
            <div className={styles.bottom}>Lorem ipsum dolor sit amet</div>
          </div>
          <div className={styles.cover2}>
            <button className={styles.button2} onClick={() => router.push('/home')}>Mulai Dari Sekarang</button>
          </div>
        </div>
      </div>
    </>
  );
}

Home.layout = "L1";

export default Home;
